jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
server:
  port: 8081

spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      uri: mongodb://localhost:27017/leavedb

  mvc:
    pathmatch:
        matching-strategy: ANT_PATH_MATCHER

  main:
    allow-bean-definition-overriding: true





