#jwt:
#  secret: fred
server:
  port: 8081


spring:
  data:
    mongodb:
      authentication-database: admin
      port: 27017
      database: leavedb
      host: localhost
      password: password
      username: admin
      auto-index-creation: true
      uri: mongodb://localhost:27017/leavedb

  mvc:
    pathmatch:
        matching-strategy: ANT_PATH_MATCHER

  main:
    allow-bean-definition-overriding: true





